module.exports = {
    FB_PAGE_TOKEN: 'EAAOoCZAP9iwgBAE1xB2Q8PK5wVEwX6oeZCHFlNjqpEuxq22z4Yrytnlf9NvKeQzoxOMoVzSJkNzuJKwPCSKGDxdpzHERTFxWktonOmJQhQTbZApiQTZBMxpKHatODZCK5OU9VY4eOdRX0a6R8YgbB3vtNo4v35PcAXuZCZBByzu2CZBDKa2Y8Wgx',
    FB_VERIFY_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: '',
    GOOGLE_PROJECT_ID: '',
    DF_LANGUAGE_CODE: '',
    GOOGLE_CLIENT_EMAIL: '',
    GOOGLE_PRIVATE_KEY: ''
};